from .attention import AttentionFusionHead
from .linear_old import LinearFusionHeadSmallOldNoAlpha, LinearFusionHeadBaseOldNoAlpha, LinearFusionHeadSmallOldOneAlpha, LinearFusionHeadBaseOldOneAlpha, LinearFusionHeadBaseOldThreeAlphas
from .linear import LinearFusionHeadSmall, LinearFusionHeadBase